on:
  push:
    branches:
      - main

name: "Release Please"

permissions:
  contents: write
  pull-requests: write

jobs:
  filter:
    name: 'Check if source files have changed'
    runs-on: ubuntu-latest
    outputs:
      assets: ${{ steps.filter.outputs.assets }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'src/**'

  build-assets:
    if: steps.changes.outputs.src == 'true'
    name: Build front-end assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - run: npm run build --production

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore(assets): built front-end assets [skip-ci]" && git push
          else
            echo "No changes to commit."
          fi

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: 'release-please-config.json'
          manifest-file: '.release-please-manifest.json'
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
